nguage: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: required
dist: trusty
cache:
directories:
             - "~/.platformio"
env:
             - PLATFORMIO_CI_SRC=src/
addons:
	apt:
		packages:
			g++5
install:
        sudo  pip install -U platformio
         
script:
         - mkdir build
         - cd build
         - cmake -Dtest=ON ../
         - make
         - make test
         - ./YASM
         - ./runUnitTests
         - cd ..
         - platformio ci --board=uno
         - cd build
         - cmake -Dtest=ON -DRANGE_CHECK=0 -DSTACK_SIZE=64 ../
         - make
         - make test
         - ./YASM
         - ./runUnitTests
         - cd ..
         - platformio ci --board=uno
