language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: required
dist: trusty
cache:
	- pip
	- apt
directories:
             - "~/.platformio"
env:
             - PLATFORMIO_CI_SRC=YASM_VM/src/
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install g++-5 -y

install:
        sudo  pip install -U platformio
         
script:
         - mkdir build
         - cd build
         - cmake -Dtest=ON -DCMAKE_CXX_COMPILER=g++-5 -DSTACK_SIZE=512 ../
         - make
         - make test
         - ./runUnitTests
         - cd ..
         - platformio ci --board=uno

