nguage: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: required
cache:
directories:
             - "~/.platformio"
env:
                 - PLATFORMIO_CI_SRC=src/
install:
        sudo  pip install -U platformio
   
script:
                 - platformio ci --board=uno       
