#line 2 "D:/YASM/YASM_COMPILER/src/lexer.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 130
#define YY_END_OF_BUFFER 131
static yyconst short int yy_accept[195] =
    {   0,
        0,    0,  131,  130,  127,    1,  128,  129,  124,  126,
      125,  123,  122,  122,  122,  122,  122,  122,  122,  122,
      122,  122,  122,  122,  122,  122,  122,  127,    1,  122,
      122,  122,  122,  122,  122,  122,  122,  122,  122,  122,
      108,  122,  107,  122,  122,  122,  122,  122,  122,  122,
      122,  122,  122,  122,  122,  122,  122,  122,  122,  122,
       38,   40,   41,   39,  122,  122,   70,   72,   73,   71,
      122,  106,  122,  122,   54,   56,   57,   55,  122,  122,
      122,  122,   26,   28,   29,   27,  110,  122,  121,  122,
      122,  122,    2,    4,    5,    3,   22,   24,   25,   23,

      120,   90,   92,   93,   91,   14,   16,   17,   15,   42,
       44,   45,   43,  122,   78,   80,   81,   79,   74,   76,
       77,   75,   86,   88,   89,   87,   62,   64,   65,   63,
      122,   58,   60,   61,   59,   10,   12,   13,   11,   94,
       96,   97,   95,   46,   48,   49,   47,  102,  104,  105,
      103,  116,  118,  119,  117,  109,   34,   36,   37,   35,
       30,   32,   33,   31,    6,    8,    9,    7,   18,   20,
       21,   19,  111,   82,   84,   85,   83,   66,   68,   69,
       67,   98,  100,  101,   99,   50,   52,   53,   51,  112,
      114,  115,  113,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    1,    1,    5,
        6,    7,    8,    1,    9,    1,   10,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    1,    1,    1,
        1,    1,    1,    1,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
        1,    1,    1,    1,    1,    1,   13,   14,   15,   16,

       17,   18,   19,   20,   21,   22,   12,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   12,   12,
       12,   12,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[34] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3
    } ;

static yyconst short int yy_base[197] =
    {   0,
        0,    0,  204,  205,   32,    0,  205,  205,  205,  205,
      205,  205,    0,   20,  190,   20,   10,   23,  177,   24,
       26,  169,   27,  171,   20,  182,   27,   47,    0,    0,
      182,  181,  173,  180,  161,   42,  180,  164,   46,  176,
        0,  163,    0,  161,  162,   47,  164,   43,  154,   52,
      155,  151,  149,   35,  165,   60,   64,  152,   65,   70,
        0,    0,    0,   75,  142,   78,    0,    0,    0,   83,
       88,    0,   89,  132,    0,    0,    0,   93,  101,  106,
      107,  111,    0,    0,    0,    0,  112,  120,    0,  124,
      125,  129,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,  130,    0,
        0,    0,    0,  100,    0,    0,    0,  135,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  143,
      147,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  148,    0,    0,    0,
        0,    0,    0,    0,    0,  153,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  205,  183,   77

    } ;

static yyconst short int yy_def[197] =
    {   0,
      194,    1,  194,  194,  194,  195,  194,  194,  194,  194,
      194,  194,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  194,  195,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,

      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,    0,  194,  194

    } ;

static yyconst short int yy_nxt[239] =
    {   0,
        4,    5,    5,    6,    7,    8,    9,   10,   11,   12,
        4,   13,   14,   13,   15,   16,   17,   13,   18,   13,
       19,   20,   21,   22,   23,   24,   25,   13,   26,   27,
       13,   13,   13,   28,   28,   31,   34,   36,   37,   38,
       35,   41,   44,   48,   32,   51,   54,   42,   28,   28,
       45,   52,   49,   39,   43,   61,   46,   90,   55,   67,
       75,   80,   62,   91,   63,   83,   68,   76,   69,   77,
       81,   64,   84,   93,   85,   70,   78,   97,  102,   30,
       94,   86,   95,  106,   98,  103,   99,  104,  110,   96,
      107,  115,  108,  100,  105,  111,  119,  112,  116,  109,

      117,  123,  127,  120,  113,  121,  132,  118,  124,  128,
      125,  129,  122,  133,  136,  134,  173,  126,  130,  140,
      144,  137,  135,  138,  148,  152,  141,  145,  142,  146,
      139,  149,  153,  150,  154,  143,  147,  157,  161,  156,
      151,  155,  165,  169,  158,  162,  159,  163,  174,  166,
      170,  167,  171,  160,  164,  175,  178,  176,  168,  172,
      182,  186,  131,  179,  177,  180,  190,  183,  187,  184,
      188,  114,  181,  191,  101,  192,  185,  189,   92,   89,
       88,   87,  193,   29,   82,   29,   79,   74,   73,   72,
       71,   66,   65,   60,   59,   58,   57,   56,   53,   50,

       47,   40,   33,  194,    3,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194
    } ;

static yyconst short int yy_chk[239] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    5,   14,   16,   17,   17,   18,
       16,   20,   21,   23,   14,   25,   27,   20,   28,   28,
       21,   25,   23,   18,   20,   36,   21,   54,   27,   39,
       46,   48,   36,   54,   36,   50,   39,   46,   39,   46,
       48,   36,   50,   56,   50,   39,   46,   57,   59,  196,
       56,   50,   56,   60,   57,   59,   57,   59,   64,   56,
       60,   66,   60,   57,   59,   64,   70,   64,   66,   60,

       66,   71,   73,   70,   64,   70,   78,   66,   71,   73,
       71,   73,   70,   78,   79,   78,  114,   71,   73,   80,
       81,   79,   78,   79,   82,   87,   80,   81,   80,   81,
       79,   82,   87,   82,   87,   80,   81,   90,   91,   88,
       82,   87,   92,  109,   90,   91,   90,   91,  118,   92,
      109,   92,  109,   90,   91,  118,  130,  118,   92,  109,
      131,  147,   74,  130,  118,  130,  156,  131,  147,  131,
      147,   65,  130,  156,   58,  156,  131,  147,   55,   53,
       52,   51,  156,  195,   49,  195,   47,   45,   44,   42,
       40,   38,   37,   35,   34,   33,   32,   31,   26,   24,

       22,   19,   15,    3,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "YASM_COMPILER/src/yasm.lex"
#define INITIAL 0
#line 3 "YASM_COMPILER/src/yasm.lex"
#include <stdio.h>
#include "../../YASM_VM/src/command.h"


        //        ADD_BYTE, ADD_SHORT, ADD_INT, ADD_LONG,
        //        SUB_BYTE, SUB_SHORT, SUB_INT, SUB_LONG,
        //        MUL_BYTE, MUL_SHORT, MUL_INT, MUL_LONG,
        //        DIV_BYTE, DIV_SHORT, DIV_INT, DIV_LONG, DIV_SBYTE, DIV_SSHORT, DIV_SINT, DIV_SLONG,
        //        AND_BYTE, AND_SHORT, AND_INT, AND_LONG,
        //        OR_BYTE, OR_SHORT, OR_INT, OR_LONG,
        //        SHR_BYTE, SHR_SHORT, SHR_INT, SHR_LONG,
        //        SHL_BYTE, SHL_SHORT, SHL_INT, SHL_LONG,
        //        EQ_BYTE, EQ_SHORT, EQ_INT, EQ_LONG, EQ_SBYTE, EQ_SSHORT, EQ_SINT, EQ_SLONG,
        //        NEQ_BYTE, NEQ_SHORT, NEQ_INT, NEQ_LONG, NEQ_SBYTE, NEQ_SSHORT, NEQ_SINT, NEQ_SLONG,
        //        LT_BYTE, LT_SHORT, LT_INT, LT_LONG, LT_SBYTE, LT_SSHORT, LT_SINT, LT_SLONG,
        //        LEQ_BYTE, LEQ_SHORT, LEQ_INT, LEQ_LONG, LEQ_SBYTE, LEQ_SSHORT, LEQ_SINT, LEQ_SLONG,
        //        GT_BYTE, GT_SHORT, GT_INT, GT_LONG, GT_SBYTE, GT_SSHORT, GT_SINT, GT_SLONG,
        //        GEQ_BYTE, GEQ_SHORT, GEQ_INT, GEQ_LONG, GEQ_SBYTE, GEQ_SSHORT, GEQ_SINT, GEQ_SLONG,
        //        INC_BYTE, INC_SHORT, INC_INT, INC_LONG,
        //        DEC_BYTE, DEC_SHORT, DEC_INT, DEC_LONG,
        //        NEG_SBYTE, NEG_SSHORT, NEG_SINT, NEG_SLONG,
        //        LNOT_BYTE, LNOT_SHORT, LNOT_INT, LNOT_LONG,
        //        NOT_BYTE, NOT_SHORT, NOT_INT, NOT_LONG,
        //      // branch
        //        JMP, JT, JF,
        //      // mem
        //        PUSH, POP, ERASE, PUSH_BYTE, PUSH_SHORT, PUSH_INT, PUSH_LONG, POP_BYTE, POP_SHORT, POP_INT, POP_LONG,
        //      // type cast
        //         ONE_TO_TWO, ONE_TO_FOUR, TWO_TO_ONE, TWO_TO_FOUR, FOUR_TO_ONE, FOUR_TO_TWO

        typedef enum{
                _PLUS_OP = RET,
                _MINUS_OP,
                _MUL_OP,
                _DIV_OP,
                _INDENT,
                _OUTDENT,
                _LABEL
        } OPERATORS;


#define LEXER_DEBUG 0
/* Lexemes */
/* Arithmetic */
#line 528 "D:/YASM/YASM_COMPILER/src/lexer.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 209 "YASM_COMPILER/src/yasm.lex"

#line 681 "D:/YASM/YASM_COMPILER/src/lexer.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 195 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 205 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 210 "YASM_COMPILER/src/yasm.lex"
/* Ignore comments */
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 214 "YASM_COMPILER/src/yasm.lex"
{  return ADD_BYTE; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 215 "YASM_COMPILER/src/yasm.lex"
{  return ADD_SHORT; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 216 "YASM_COMPILER/src/yasm.lex"
{  return ADD_INT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 217 "YASM_COMPILER/src/yasm.lex"
{  return ADD_LONG; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 219 "YASM_COMPILER/src/yasm.lex"
{  return SUB_BYTE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 220 "YASM_COMPILER/src/yasm.lex"
{  return SUB_SHORT; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 221 "YASM_COMPILER/src/yasm.lex"
{  return SUB_INT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 222 "YASM_COMPILER/src/yasm.lex"
{  return SUB_LONG; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 224 "YASM_COMPILER/src/yasm.lex"
{  return MUL_BYTE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 225 "YASM_COMPILER/src/yasm.lex"
{  return MUL_SHORT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 226 "YASM_COMPILER/src/yasm.lex"
{  return MUL_INT; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 227 "YASM_COMPILER/src/yasm.lex"
{  return MUL_LONG; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 229 "YASM_COMPILER/src/yasm.lex"
{  return DIV_BYTE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 230 "YASM_COMPILER/src/yasm.lex"
{  return DIV_SHORT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 231 "YASM_COMPILER/src/yasm.lex"
{  return DIV_INT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 232 "YASM_COMPILER/src/yasm.lex"
{  return DIV_LONG; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 233 "YASM_COMPILER/src/yasm.lex"
{  return DIV_SBYTE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 234 "YASM_COMPILER/src/yasm.lex"
{  return DIV_SSHORT; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 235 "YASM_COMPILER/src/yasm.lex"
{  return DIV_SINT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 236 "YASM_COMPILER/src/yasm.lex"
{  return DIV_SLONG; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 238 "YASM_COMPILER/src/yasm.lex"
{  return AND_BYTE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 239 "YASM_COMPILER/src/yasm.lex"
{  return AND_SHORT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 240 "YASM_COMPILER/src/yasm.lex"
{  return AND_INT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 241 "YASM_COMPILER/src/yasm.lex"
{  return AND_LONG; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 243 "YASM_COMPILER/src/yasm.lex"
{  return OR_BYTE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 244 "YASM_COMPILER/src/yasm.lex"
{  return OR_SHORT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 245 "YASM_COMPILER/src/yasm.lex"
{  return OR_INT; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 246 "YASM_COMPILER/src/yasm.lex"
{  return OR_LONG; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 248 "YASM_COMPILER/src/yasm.lex"
{  return SHR_BYTE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 249 "YASM_COMPILER/src/yasm.lex"
{  return SHR_SHORT; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 250 "YASM_COMPILER/src/yasm.lex"
{  return SHR_INT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 251 "YASM_COMPILER/src/yasm.lex"
{  return SHR_LONG; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 253 "YASM_COMPILER/src/yasm.lex"
{  return SHL_BYTE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 254 "YASM_COMPILER/src/yasm.lex"
{  return SHL_SHORT; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 255 "YASM_COMPILER/src/yasm.lex"
{  return SHL_INT; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 256 "YASM_COMPILER/src/yasm.lex"
{  return SHL_LONG; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 258 "YASM_COMPILER/src/yasm.lex"
{  return EQ_BYTE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 259 "YASM_COMPILER/src/yasm.lex"
{  return EQ_SHORT; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 260 "YASM_COMPILER/src/yasm.lex"
{  return EQ_INT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 261 "YASM_COMPILER/src/yasm.lex"
{  return EQ_LONG; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 262 "YASM_COMPILER/src/yasm.lex"
{  return EQ_SBYTE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 263 "YASM_COMPILER/src/yasm.lex"
{  return EQ_SSHORT; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 264 "YASM_COMPILER/src/yasm.lex"
{  return EQ_SINT; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 265 "YASM_COMPILER/src/yasm.lex"
{  return EQ_SLONG; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 267 "YASM_COMPILER/src/yasm.lex"
{  return NEQ_BYTE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 268 "YASM_COMPILER/src/yasm.lex"
{  return NEQ_SHORT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 269 "YASM_COMPILER/src/yasm.lex"
{  return NEQ_INT; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 270 "YASM_COMPILER/src/yasm.lex"
{  return NEQ_LONG; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 271 "YASM_COMPILER/src/yasm.lex"
{  return NEQ_SBYTE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 272 "YASM_COMPILER/src/yasm.lex"
{  return NEQ_SSHORT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 273 "YASM_COMPILER/src/yasm.lex"
{  return NEQ_SINT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 274 "YASM_COMPILER/src/yasm.lex"
{  return NEQ_SLONG; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 276 "YASM_COMPILER/src/yasm.lex"
{  return LT_BYTE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 277 "YASM_COMPILER/src/yasm.lex"
{  return LT_SHORT; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 278 "YASM_COMPILER/src/yasm.lex"
{  return LT_INT; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 279 "YASM_COMPILER/src/yasm.lex"
{  return LT_LONG; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 280 "YASM_COMPILER/src/yasm.lex"
{  return LT_SBYTE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 281 "YASM_COMPILER/src/yasm.lex"
{  return LT_SSHORT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 282 "YASM_COMPILER/src/yasm.lex"
{  return LT_SINT; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 283 "YASM_COMPILER/src/yasm.lex"
{  return LT_SLONG; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 285 "YASM_COMPILER/src/yasm.lex"
{  return LEQ_BYTE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 286 "YASM_COMPILER/src/yasm.lex"
{  return LEQ_SHORT; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 287 "YASM_COMPILER/src/yasm.lex"
{  return LEQ_INT; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 288 "YASM_COMPILER/src/yasm.lex"
{  return LEQ_LONG; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 289 "YASM_COMPILER/src/yasm.lex"
{  return LEQ_SBYTE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 290 "YASM_COMPILER/src/yasm.lex"
{  return LEQ_SSHORT; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 291 "YASM_COMPILER/src/yasm.lex"
{  return LEQ_SINT; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 292 "YASM_COMPILER/src/yasm.lex"
{  return LEQ_SLONG; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 294 "YASM_COMPILER/src/yasm.lex"
{  return GT_BYTE; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 295 "YASM_COMPILER/src/yasm.lex"
{  return GT_SHORT; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 296 "YASM_COMPILER/src/yasm.lex"
{  return GT_INT; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 297 "YASM_COMPILER/src/yasm.lex"
{  return GT_LONG; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 298 "YASM_COMPILER/src/yasm.lex"
{  return GT_SBYTE; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 299 "YASM_COMPILER/src/yasm.lex"
{  return GT_SSHORT; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 300 "YASM_COMPILER/src/yasm.lex"
{  return GT_SINT; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 301 "YASM_COMPILER/src/yasm.lex"
{  return GT_SLONG; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 303 "YASM_COMPILER/src/yasm.lex"
{  return GEQ_BYTE; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 304 "YASM_COMPILER/src/yasm.lex"
{  return GEQ_SHORT; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 305 "YASM_COMPILER/src/yasm.lex"
{  return GEQ_INT; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 306 "YASM_COMPILER/src/yasm.lex"
{  return GEQ_LONG; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 307 "YASM_COMPILER/src/yasm.lex"
{  return GEQ_SBYTE; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 308 "YASM_COMPILER/src/yasm.lex"
{  return GEQ_SSHORT; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 309 "YASM_COMPILER/src/yasm.lex"
{  return GEQ_SINT; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 310 "YASM_COMPILER/src/yasm.lex"
{  return GEQ_SLONG; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 312 "YASM_COMPILER/src/yasm.lex"
{  return INC_BYTE; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 313 "YASM_COMPILER/src/yasm.lex"
{  return INC_SHORT; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 314 "YASM_COMPILER/src/yasm.lex"
{  return INC_INT; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 315 "YASM_COMPILER/src/yasm.lex"
{  return INC_LONG; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 317 "YASM_COMPILER/src/yasm.lex"
{  return DEC_BYTE; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 318 "YASM_COMPILER/src/yasm.lex"
{  return DEC_SHORT; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 319 "YASM_COMPILER/src/yasm.lex"
{  return DEC_INT; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 320 "YASM_COMPILER/src/yasm.lex"
{  return DEC_LONG; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 322 "YASM_COMPILER/src/yasm.lex"
{  return NEG_SBYTE; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 323 "YASM_COMPILER/src/yasm.lex"
{  return NEG_SSHORT; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 324 "YASM_COMPILER/src/yasm.lex"
{  return NEG_SINT; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 325 "YASM_COMPILER/src/yasm.lex"
{  return NEG_SLONG; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 327 "YASM_COMPILER/src/yasm.lex"
{  return LNOT_BYTE; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 328 "YASM_COMPILER/src/yasm.lex"
{  return LNOT_SHORT; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 329 "YASM_COMPILER/src/yasm.lex"
{  return LNOT_INT; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 330 "YASM_COMPILER/src/yasm.lex"
{  return LNOT_LONG; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 332 "YASM_COMPILER/src/yasm.lex"
{  return NOT_BYTE; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 333 "YASM_COMPILER/src/yasm.lex"
{  return NOT_SHORT; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 334 "YASM_COMPILER/src/yasm.lex"
{  return NOT_INT; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 335 "YASM_COMPILER/src/yasm.lex"
{  return NOT_LONG; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 338 "YASM_COMPILER/src/yasm.lex"
{  return JMP; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 339 "YASM_COMPILER/src/yasm.lex"
{  return JT; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 340 "YASM_COMPILER/src/yasm.lex"
{  return JF; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 342 "YASM_COMPILER/src/yasm.lex"
{  return PUSH; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 343 "YASM_COMPILER/src/yasm.lex"
{  return POP; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 344 "YASM_COMPILER/src/yasm.lex"
{  return ERASE; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 345 "YASM_COMPILER/src/yasm.lex"
{  return PUSH_BYTE; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 346 "YASM_COMPILER/src/yasm.lex"
{  return PUSH_SHORT; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 347 "YASM_COMPILER/src/yasm.lex"
{  return PUSH_INT; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 348 "YASM_COMPILER/src/yasm.lex"
{  return PUSH_LONG; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 349 "YASM_COMPILER/src/yasm.lex"
{  return POP_BYTE; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 350 "YASM_COMPILER/src/yasm.lex"
{  return POP_SHORT; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 351 "YASM_COMPILER/src/yasm.lex"
{  return POP_INT; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 352 "YASM_COMPILER/src/yasm.lex"
{  return POP_LONG; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 354 "YASM_COMPILER/src/yasm.lex"
{  return ADD_LONG; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 355 "YASM_COMPILER/src/yasm.lex"
{  return ADD_LONG; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 356 "YASM_COMPILER/src/yasm.lex"
{ printf("id"); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 361 "YASM_COMPILER/src/yasm.lex"
{return _DIV_OP;  }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 362 "YASM_COMPILER/src/yasm.lex"
{return _MUL_OP;  }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 363 "YASM_COMPILER/src/yasm.lex"
{return _MINUS_OP;  }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 364 "YASM_COMPILER/src/yasm.lex"
{return _PLUS_OP; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 365 "YASM_COMPILER/src/yasm.lex"
/* Ignore whitespace */
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 366 "YASM_COMPILER/src/yasm.lex"
return _INDENT;
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 367 "YASM_COMPILER/src/yasm.lex"
return _OUTDENT;
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 370 "YASM_COMPILER/src/yasm.lex"
ECHO;
	YY_BREAK
#line 1414 "D:/YASM/YASM_COMPILER/src/lexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 195 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 195 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 194);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 370 "YASM_COMPILER/src/yasm.lex"

int main()
{
        yylex();
        return 0;
}
