#ifndef _COMMAND_H
#define _COMMAND_H
#include "config.h"

typedef enum 
{

  ADD_BYTE, ADD_SHORT, ADD_INT, ADD_LONG,
  SUB_BYTE, SUB_SHORT, SUB_INT, SUB_LONG,
  MUL_BYTE, MUL_SHORT, MUL_INT, MUL_LONG,
  DIV_BYTE, DIV_SHORT, DIV_INT, DIV_LONG, DIV_SBYTE, DIV_SSHORT, DIV_SINT, DIV_SLONG,
  AND_BYTE, AND_SHORT, AND_INT, AND_LONG, 
  OR_BYTE, OR_SHORT, OR_INT, OR_LONG, 
  SHR_BYTE, SHR_SHORT, SHR_INT, SHR_LONG,
  SHL_BYTE, SHL_SHORT, SHL_INT, SHL_LONG,
  EQ_BYTE, EQ_SHORT, EQ_INT, EQ_LONG, EQ_SBYTE, EQ_SSHORT, EQ_SINT, EQ_SLONG,
  NEQ_BYTE, NEQ_SHORT, NEQ_INT, NEQ_LONG, NEQ_SBYTE, NEQ_SSHORT, NEQ_SINT, NEQ_SLONG,
  LT_BYTE, LT_SHORT, LT_INT, LT_LONG, LT_SBYTE, LT_SSHORT, LT_SINT, LT_SLONG,
  LEQ_BYTE, LEQ_SHORT, LEQ_INT, LEQ_LONG, LEQ_SBYTE, LEQ_SSHORT, LEQ_SINT, LEQ_SLONG,
  GT_BYTE, GT_SHORT, GT_INT, GT_LONG, GT_SBYTE, GT_SSHORT, GT_SINT, GT_SLONG,
  GEQ_BYTE, GEQ_SHORT, GEQ_INT, GEQ_LONG, GEQ_SBYTE, GEQ_SSHORT, GEQ_SINT, GEQ_SLONG,
  INC_BYTE, INC_SHORT, INC_INT, INC_LONG,
  DEC_BYTE, DEC_SHORT, DEC_INT, DEC_LONG,
  NEG_SBYTE, NEG_SSHORT, NEG_SINT, NEG_SLONG,
  LNOT_BYTE, LNOT_SHORT, LNOT_INT, LNOT_LONG,
  NOT_BYTE, NOT_SHORT, NOT_INT, NOT_LONG,

  JMP, JT, JF,

  PUSH, POP, ERASE, PUSH_BYTE, PUSH_SHORT, PUSH_INT, PUSH_LONG, POP_BYTE, POP_SHORT, POP_INT, POP_LONG,

   ONE_TO_TWO, ONE_TO_FOUR, TWO_TO_ONE, TWO_TO_FOUR, FOUR_TO_ONE, FOUR_TO_TWO,

   CALL,
   END
} COMMANDS;



#endif /* COMMAND_H */

