#ifndef _COMMAND_H
#define _COMMAND_H
#include "config.h"

typedef enum 
{
 // arithmetic and logic:
  ADD_BYTE, ADD_SHORT, ADD_INT, ADD_LONG, ADD_SBYTE, ADD_SSHORT, ADD_SINT, ADD_SLONG,
  SUB_BYTE, SUB_SHORT, SUB_INT, SUB_LONG, SUB_SBYTE, SUB_SSHORT, SUB_SINT, SUB_SLONG,
  MUL_BYTE, MUL_SHORT, MUL_INT, MUL_LONG, MUL_SBYTE, MUL_SSHORT, MUL_SINT, MUL_SLONG,
  DIV_BYTE, DIV_SHORT, DIV_INT, DIV_LONG, DIV_SBYTE, DIV_SSHORT, DIV_SINT, DIV_SLONG,
  AND_BYTE, AND_SHORT, AND_INT, AND_LONG, 
  OR_BYTE, OR_SHORT, OR_INT, OR_LONG, 
  SHR_BYTE, SHR_SHORT, SHR_INT, SHR_LONG,
  SHL_BYTE, SHL_SHORT, SHL_INT, SHL_LONG,
  EQ_BYTE, EQ_SHORT, EQ_INT, EQ_LONG,
  NEQ_BYTE, NEQ_SHORT, NEQ_INT, NEQ_LONG,
  LT_BYTE, LT_SHORT, LT_INT, LT_LONG, LT_SBYTE, LT_SSHORT, LT_SINT, LT_SLONG,
  LEQ_BYTE, LEQ_SHORT, LEQ_INT, LEQ_LONG, LEQ_SBYTE, LEQ_SSHORT, LEQ_SINT, LEQ_SLONG,
  GT_BYTE, GT_SHORT, GT_INT, GT_LONG, GT_SBYTE, GT_SSHORT, GT_SINT, GT_SLONG,
  GEQ_BYTE, GEQ_SHORT, GEQ_INT, GEQ_LONG, GEQ_SBYTE, GEQ_SSHORT, GEQ_SINT, GEQ_SLONG,
  INC_BYTE, INC_SHORT, INC_INT, INC_LONG, INC_SBYTE, INC_SSHORT, INC_SINT, INC_SLONG,
  DEC_BYTE, DEC_SHORT, DEC_INT, DEC_LONG, DEC_SBYTE, DEC_SSHORT, DEC_SINT, DEC_SLONG,
  NEG_BYTE, NEG_SHORT, NEG_INT, NEG_LONG, NEG_SBYTE, NEG_SSHORT, NEG_SINT, NEG_SLONG,
  NOT_BYTE, NOT_SHORT, NOT_INT, NOT_LONG,
// branch
  JMP, JE, JNE,
// mem
  PUSH, POP, ERASE,
// type cast
   ONE_TO_TWO, ONE_TO_FOUR, TWO_TO_ONE, TWO_TO_FOUR, FOUR_TO_ONE, FOUR_TO_TWO
} COMMANDS;



#endif /* COMMAND_H */

